spring:
  application:
    name: encoding-service
  kafka:
    bootstrap-server: 9092
    consumer:
      group-id: encoding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: "*"
        use:
          type:
            headers: false
        value:
          default:
            type: com.vsp.encodingservice.event.VideoUploadEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

#aws configuration
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}

#FFmpe configuration
ffmpeg:
  path: ${FFMPEG_PATH}

#Temp directory for encoding
encoding:
  base-path: ${TEMP_DIR}

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info