spring:
  application:
    name: streaming-service

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    group-id: streaming-service-group
    auto-offset-reset: earliest
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"
#          use:
#            type:
#              headers: false
#          value:
#            default:
#              type: com.vsp.streamingservice.event.VideoEncodedEvent



server:
  port: 8084

#aws configuration
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
    presigned-url-expiry: ${AWS_S3_PRESIGNED_URL_EXPIRY:60}

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
